### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [Microsoft/X-Mem#14]
I would like to point out that identifiers like "[`__use_sequential_kernel_fptr`](https://github.com/Microsoft/X-Mem/blob/3197210a05e3c58693f41bfbb3483780b19e5f57/src/include/LoadWorker.h#L90)" and "[`__POWER_READER_H`](https://github.com/Microsoft/X-Mem/blob/1e4f24c38c488bfbae2fce40d35820dff666ccad/src/include/PowerReader.h#L32)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier) to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by mgottscho** [comment]
Hi elfring,

Thanks for the feedback on X-Mem. v2.4.1 now has, among other changes, renamed variables, functions, and pre-processor macros to eliminate the use of double underscores or leading underscores anywhere in the code. Hopefully it now complies with recommended naming conventions!

Mark

**Comment by elfring** [comment]
Thanks for your source code improvement.
