### ISSUE TITLE
Catch exceptions in main()?

### ISSUE THREAD

**Issue by elfring** [Microsoft/X-Mem#15]
I expect that exception handling is usually supported by a C++ program. I wonder why your function "[main](https://github.com/Microsoft/X-Mem/blob/5dc88ae87aaa1399bb6df732217d38b4f40639d4/src/main.cpp#L87)" does not contain [corresponding try and catch instructions](http://stackoverflow.com/questions/368184/does-it-make-sense-to-catch-exceptions-in-the-main) so far.

How do you think about recommendations by Matthew Wilson in [an article](http://accu.org/index.php/journals/1706)?

Would you like to adjust the implementation if you consider [effects for uncaught/unhandled exceptions](http://www.informit.com/guides/content.aspx?g=cplusplus&seqNum=108) like they are described by Danny Kalev?

**Comment by mgottscho** [comment]
Hi elfring,

Thanks for the feedback on X-Mem. v2.4.1 now has general exception catching in main() as you suggested. When I find more time I hope to add exception support throughout the codebase in general. Currently error-handling is more in the "C-style" of programming.

Mark
