### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [Microsoft/X-Mem#16]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null) like the following.
- [Configurator::configureFromInput](https://github.com/Microsoft/X-Mem/blob/a6424d181fa4ed9b370540b61d6169d095b5fa8c/src/Configurator.cpp#L684)
- [BenchmarkManager](https://github.com/Microsoft/X-Mem/blob/a6424d181fa4ed9b370540b61d6169d095b5fa8c/src/BenchmarkManager.cpp#L143)
- [WindowsDRAMPowerReader](https://github.com/Microsoft/X-Mem/blob/a6424d181fa4ed9b370540b61d6169d095b5fa8c/src/win/WindowsDRAMPowerReader.cpp#L64)

**Comment by mgottscho** [comment]
Hi elfring,

Thanks for the feedback on X-Mem. I found the time to fix these unnecessary null pointer checks in v2.4.1.

Mark

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/Microsoft/X-Mem/commit/74483a8908ce910b9288ccb0dfcf69bdcd0e1615).
